# (C) Copyright 2020

version: '3.3'

services:
    db:
      image: postgres
      container_name: postgres
      restart: unless-stopped
      env_file:
        ./db_con_info.env
      volumes:
        - db_data:/var/lib/postgresql/data
      ports:
        - 5432:5432
      networks:
        - db_net
        - db_admin

    adminer:
      depends_on:
        - db
      image: adminer
      container_name: adminer
      restart: unless-stopped
      ports:
        - 8080:8080
      networks:
        - db_admin

    web_service:
      depends_on:
        - db
      build: ./server
      container_name: web_service
      restart: unless-stopped
      env_file:
        ./db_con_info.env
      environment:
        - WEB_SERVICE_ADDR=0.0.0.0
        - WEB_SERVICE_PORT=80
      ports:
        - 3333:80
      networks:
        - db_net

volumes:
    db_data: {}

networks:
    db_net: {}
    db_admin: {}
